# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 21:38
from __future__ import unicode_literals

import advisingApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('EMAIL', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='chooses',
            fields=[
                ('PID', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('DegreeTitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='contains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Title', models.CharField(max_length=100)),
                ('Degree_Title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('TITLE', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[advisingApp.models.validate_Cname])),
                ('Type', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Grade_Needed', models.CharField(max_length=10, validators=[advisingApp.models.validate_Grade])),
                ('Credits', models.IntegerField(validators=[advisingApp.models.validate_credits])),
                ('Tier', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Degrees',
            fields=[
                ('TITLE', models.CharField(max_length=50, primary_key=True, serialize=False, validators=[advisingApp.models.validate_Dname])),
                ('About', models.TextField()),
                ('Requiured_Credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('Name', models.TextField(max_length=100)),
                ('DEPT_NUM', models.IntegerField(primary_key=True, serialize=False)),
                ('Building', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisites',
            fields=[
                ('TITLE', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[advisingApp.models.validate_Cname])),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisingApp.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('PID', models.CharField(max_length=9, primary_key=True, serialize=False, validators=[advisingApp.models.validate_PID])),
                ('Email', models.EmailField(max_length=100)),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('Years_To_Completion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('AdvisorEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisingApp.Advisor')),
            ],
        ),
        migrations.CreateModel(
            name='takes',
            fields=[
                ('PID', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('Grade_Received', models.CharField(blank=True, max_length=3, validators=[advisingApp.models.validate_Grade])),
                ('Enrolled', models.BooleanField()),
                ('Course_Title', models.ManyToManyField(to='advisingApp.Courses')),
            ],
        ),
        migrations.AddField(
            model_name='degrees',
            name='Deparment_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisingApp.Departments'),
        ),
    ]
