# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='takes',
            name='Tier1comp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='takes',
            name='Tier1jc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='takes',
            name='Tier1qs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='takes',
            name='Tier2',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='takes',
            name='Tier3',
            field=models.BooleanField(default=False),
        ),
    ]
