# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisingApp', '0002_auto_20160725_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='takes',
            name='CrossCulture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='takes',
            name='FineArts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='takes',
            name='Humanities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='takes',
            name='NaturalScience',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='takes',
            name='ScienceMath',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='takes',
            name='SocialScience',
            field=models.BooleanField(default=False),
        ),
    ]
