# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisingApp', '0003_auto_20160725_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='takes',
            name='FreeElectives',
            field=models.BooleanField(default=False),
        ),
    ]
