# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 18:36
from __future__ import unicode_literals

import advisingApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisingApp', '0005_auto_20160726_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='discription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='TITLE',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[advisingApp.models.validate_Cname]),
        ),
    ]
