# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 21:04
from __future__ import unicode_literals

import advisingApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisingApp', '0006_auto_20160804_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='TITLE',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, validators=[advisingApp.models.validate_Cname]),
        ),
    ]
